# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WashU Ticket Share' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WashU Ticket Share
  pod 'Firebase/Database'
  pod 'Firebase/Auth' 
  pod 'MessageKit'
end
